# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: blog@minimal.com.br
description: Esse blog é uma implementação de desenvolvimento com o Jekyll. Espero que gostem !
baseurl: "" 
url: "https://alanoteles.github.io/" # the base hostname & protocol for your site
twitter_username: minimal_twitter
github_username:  minimal-github

# Build settings
markdown: kramdown
permalink: /:title
